// buscar producto por id
GET localhost:8080/parametros/1


###
// lista los productos con precio mayor al dado
GET localhost:8080/precio/700



###
POST localhost:8080/addProduct
Content-Type: application/json

{
  "name": "yyy",
  "quantity": 439,
  "code_value": "S82254D57854",
  "is_published": true,
  "expiration": "15/12/2021",
  "price": 71.42
}


###
PUT localhost:8080/updateProduct
Content-Type: application/json

{
  "id": 1,
  "name": "Oil - Margarine1.1",
  "quantity": 439,
  "code_value": "S82254D",
  "is_published": true,
  "expiration": "15/12/2021",
  "price": 71.42
}