// buscar producto por id
GET localhost:8080/parametros/1


###
// lista los productos con precio mayor al dado
GET localhost:8080/precio/700



###
POST localhost:8080/addProduct
Content-Type: application/json

{
  "name": "yyy",
  "quantity": 439,
  "code_value": "S82254D57854",
  "is_published": true,
  "expiration": "15/12/2021",
  "price": 71.42
}


###
PUT localhost:8080/updateProduct
Content-Type: application/json

{
  "id": 2,
  "name": "Pineapple - Canned",
  "quantity": 345,
  "code_value": "M4637",
  "is_published": true,
  "expiration": "09/08/2021",
  "price": 352.79
}

###
PATCH localhost:8080/patchPrice
Content-Type: application/json

{
  "id": 2,
  "price": "banana"
}


###
DELETE localhost:8080/deleteProduct/509